insert into place (id, name, country_id) values (1, 'Bellgrove', 1);
insert into place (id, name, country_id) values (2, 'Texas', 2);
insert into place (id, name, country_id) values (3, 'Acker', 3);
insert into place (id, name, country_id) values (4, 'Tennyson', 4);
insert into place (id, name, country_id) values (5, 'Harper', 5);
insert into place (id, name, country_id) values (6, 'Green Ridge', 6);
insert into place (id, name, country_id) values (7, 'Milwaukee', 7);
insert into place (id, name, country_id) values (8, 'Eastwood', 8);
insert into place (id, name, country_id) values (9, 'Bobwhite', 9);
insert into place (id, name, country_id) values (10, 'Lakeland', 10);
insert into place (id, name, country_id) values (11, 'Clarendon', 11);
insert into place (id, name, country_id) values (12, 'Summer Ridge', 12);
insert into place (id, name, country_id) values (13, 'Eagan', 13);
insert into place (id, name, country_id) values (14, 'Meadow Ridge', 14);
insert into place (id, name, country_id) values (15, 'Straubel', 15);
insert into place (id, name, country_id) values (16, 'Messerschmidt', 16);
insert into place (id, name, country_id) values (17, 'Westerfield', 17);
insert into place (id, name, country_id) values (18, 'Hazelcrest', 18);
insert into place (id, name, country_id) values (19, 'New Castle', 19);
insert into place (id, name, country_id) values (20, 'Morrow', 20);
insert into place (id, name, country_id) values (21, 'Kedzie', 21);
insert into place (id, name, country_id) values (22, 'Blue Bill Park', 22);
insert into place (id, name, country_id) values (23, 'Hermina', 23);
insert into place (id, name, country_id) values (24, 'Messerschmidt', 24);
insert into place (id, name, country_id) values (25, 'Caliangt', 25);
insert into place (id, name, country_id) values (26, 'Rockefeller', 26);
insert into place (id, name, country_id) values (27, 'Montana', 27);
insert into place (id, name, country_id) values (28, 'Cordelia', 28);
insert into place (id, name, country_id) values (29, 'Little Fleur', 29);
insert into place (id, name, country_id) values (30, 'Riverside', 30);
insert into place (id, name, country_id) values (31, 'Hagan', 31);
insert into place (id, name, country_id) values (32, 'Anthes', 32);
insert into place (id, name, country_id) values (33, 'Welch', 33);
insert into place (id, name, country_id) values (34, 'Nova', 34);
insert into place (id, name, country_id) values (35, 'Haas', 35);
insert into place (id, name, country_id) values (36, 'Hudson', 36);
insert into place (id, name, country_id) values (37, 'Derek', 37);
insert into place (id, name, country_id) values (38, 'Sunfield', 38);
insert into place (id, name, country_id) values (39, 'Kropf', 39);
insert into place (id, name, country_id) values (40, 'Columbus', 40);
insert into place (id, name, country_id) values (41, 'Sheridan', 41);
insert into place (id, name, country_id) values (42, 'Lukken', 42);
insert into place (id, name, country_id) values (43, 'Burning Wood', 43);
insert into place (id, name, country_id) values (44, 'Everett', 44);
insert into place (id, name, country_id) values (45, 'Erie', 45);
insert into place (id, name, country_id) values (46, 'Laurel', 46);
insert into place (id, name, country_id) values (47, 'North', 47);
insert into place (id, name, country_id) values (48, 'Dixon', 48);
insert into place (id, name, country_id) values (49, 'Magdeline', 49);
insert into place (id, name, country_id) values (50, 'Magdeline', 50);
insert into place (id, name, country_id) values (51, 'Mcguire', 51);
insert into place (id, name, country_id) values (52, 'Gale', 52);
insert into place (id, name, country_id) values (53, 'Main', 53);
insert into place (id, name, country_id) values (54, 'Warrior', 54);
insert into place (id, name, country_id) values (55, 'Lyons', 55);
insert into place (id, name, country_id) values (56, 'Esch', 56);
insert into place (id, name, country_id) values (57, 'Melvin', 57);
insert into place (id, name, country_id) values (58, 'Sycamore', 58);
insert into place (id, name, country_id) values (59, 'Straubel', 59);
insert into place (id, name, country_id) values (60, 'Bayside', 60);
insert into place (id, name, country_id) values (61, 'Farwell', 61);
insert into place (id, name, country_id) values (62, 'Bay', 62);
insert into place (id, name, country_id) values (63, 'Commercial', 63);
insert into place (id, name, country_id) values (64, 'Anthes', 64);
insert into place (id, name, country_id) values (65, 'Ruskin', 65);
insert into place (id, name, country_id) values (66, 'Valley Edge', 66);
insert into place (id, name, country_id) values (67, 'Crownhardt', 67);
insert into place (id, name, country_id) values (68, 'High Crossing', 68);
insert into place (id, name, country_id) values (69, 'Erie', 69);
insert into place (id, name, country_id) values (70, 'Express', 70);
insert into place (id, name, country_id) values (71, 'Ridge Oak', 71);
insert into place (id, name, country_id) values (72, 'Myrtle', 72);
insert into place (id, name, country_id) values (73, 'Onsgard', 73);
insert into place (id, name, country_id) values (74, 'American Ash', 74);
insert into place (id, name, country_id) values (75, 'Roth', 75);
insert into place (id, name, country_id) values (76, 'Harbort', 76);
insert into place (id, name, country_id) values (77, 'Russell', 77);
insert into place (id, name, country_id) values (78, 'Del Sol', 78);
insert into place (id, name, country_id) values (79, 'Katie', 79);
insert into place (id, name, country_id) values (80, 'Maywood', 80);
insert into place (id, name, country_id) values (81, 'Schmedeman', 81);
insert into place (id, name, country_id) values (82, 'Karstens', 82);
insert into place (id, name, country_id) values (83, 'Portage', 83);
insert into place (id, name, country_id) values (84, 'Nelson', 84);
insert into place (id, name, country_id) values (85, 'Goodland', 85);
insert into place (id, name, country_id) values (86, 'Orin', 86);
insert into place (id, name, country_id) values (87, 'Badeau', 87);
insert into place (id, name, country_id) values (88, 'Springview', 88);
insert into place (id, name, country_id) values (89, 'Hansons', 89);
insert into place (id, name, country_id) values (90, 'Debs', 90);
insert into place (id, name, country_id) values (91, 'Annamark', 91);
insert into place (id, name, country_id) values (92, 'Buell', 92);
insert into place (id, name, country_id) values (93, 'Bartelt', 93);
insert into place (id, name, country_id) values (94, 'Union', 94);
insert into place (id, name, country_id) values (95, 'Ilene', 95);
insert into place (id, name, country_id) values (96, 'Blue Bill Park', 96);
insert into place (id, name, country_id) values (97, 'Sullivan', 97);
insert into place (id, name, country_id) values (98, 'Meadow Ridge', 98);
insert into place (id, name, country_id) values (99, 'Melody', 99);
insert into place (id, name, country_id) values (100, 'Badeau', 100);
insert into place (id, name, country_id) values (101, 'Sutteridge', 101);
insert into place (id, name, country_id) values (102, 'Lerdahl', 102);
insert into place (id, name, country_id) values (103, 'Menomonie', 103);
insert into place (id, name, country_id) values (104, 'Arizona', 104);
insert into place (id, name, country_id) values (105, 'Holy Cross', 105);
insert into place (id, name, country_id) values (106, 'Anzinger', 106);
insert into place (id, name, country_id) values (107, 'Village', 107);
insert into place (id, name, country_id) values (108, 'Holmberg', 108);
insert into place (id, name, country_id) values (109, 'Forest', 109);
insert into place (id, name, country_id) values (110, 'Straubel', 110);
insert into place (id, name, country_id) values (111, 'Schlimgen', 111);
insert into place (id, name, country_id) values (112, 'Ridge Oak', 112);
insert into place (id, name, country_id) values (113, 'Kenwood', 113);
insert into place (id, name, country_id) values (114, 'Vidon', 114);
insert into place (id, name, country_id) values (115, 'Maywood', 115);
insert into place (id, name, country_id) values (116, 'Logan', 116);
insert into place (id, name, country_id) values (117, 'Service', 117);
insert into place (id, name, country_id) values (118, 'Park Meadow', 118);
insert into place (id, name, country_id) values (119, 'Graedel', 119);
insert into place (id, name, country_id) values (120, 'Magdeline', 120);
insert into place (id, name, country_id) values (121, 'Bultman', 121);
insert into place (id, name, country_id) values (122, 'Susan', 122);
insert into place (id, name, country_id) values (123, 'Pennsylvania', 123);
insert into place (id, name, country_id) values (124, 'Bluejay', 124);
insert into place (id, name, country_id) values (125, 'Blackbird', 125);
insert into place (id, name, country_id) values (126, 'Muir', 126);
insert into place (id, name, country_id) values (127, 'Southridge', 127);
insert into place (id, name, country_id) values (128, 'Wayridge', 128);
insert into place (id, name, country_id) values (129, 'Elmside', 129);
insert into place (id, name, country_id) values (130, 'Packers', 130);
insert into place (id, name, country_id) values (131, 'Wayridge', 131);
insert into place (id, name, country_id) values (132, 'Village', 132);
insert into place (id, name, country_id) values (133, 'Hauk', 133);
insert into place (id, name, country_id) values (134, 'Meadow Ridge', 134);
insert into place (id, name, country_id) values (135, 'Arrowood', 135);
insert into place (id, name, country_id) values (136, 'South', 136);
insert into place (id, name, country_id) values (137, 'Westport', 137);
insert into place (id, name, country_id) values (138, 'Jenna', 138);
insert into place (id, name, country_id) values (139, 'Burrows', 139);
insert into place (id, name, country_id) values (140, 'Ridgeview', 140);
insert into place (id, name, country_id) values (141, 'Kinsman', 141);
insert into place (id, name, country_id) values (142, 'Mitchell', 142);
insert into place (id, name, country_id) values (143, 'Golf', 143);
insert into place (id, name, country_id) values (144, 'Milwaukee', 144);
insert into place (id, name, country_id) values (145, 'Old Shore', 145);
insert into place (id, name, country_id) values (146, 'Redwing', 146);
insert into place (id, name, country_id) values (147, 'Paget', 147);
insert into place (id, name, country_id) values (148, 'Scofield', 148);
insert into place (id, name, country_id) values (149, 'High Crossing', 149);
insert into place (id, name, country_id) values (150, 'Donald', 150);
insert into place (id, name, country_id) values (151, 'Golf View', 151);
insert into place (id, name, country_id) values (152, 'Canary', 152);
insert into place (id, name, country_id) values (153, 'Blaine', 153);
insert into place (id, name, country_id) values (154, 'Walton', 154);
insert into place (id, name, country_id) values (155, 'Vidon', 155);
insert into place (id, name, country_id) values (156, 'David', 156);
insert into place (id, name, country_id) values (157, 'Doe Crossing', 157);
insert into place (id, name, country_id) values (158, 'East', 158);
insert into place (id, name, country_id) values (159, 'Bunker Hill', 159);
insert into place (id, name, country_id) values (160, 'Washington', 160);
insert into place (id, name, country_id) values (161, 'Sunnyside', 161);
insert into place (id, name, country_id) values (162, 'Express', 162);
insert into place (id, name, country_id) values (163, 'Nevada', 163);
insert into place (id, name, country_id) values (164, 'Darwin', 164);
insert into place (id, name, country_id) values (165, 'Atwood', 165);
insert into place (id, name, country_id) values (166, 'Grim', 166);
insert into place (id, name, country_id) values (167, 'Basil', 167);
insert into place (id, name, country_id) values (168, 'Bunting', 168);
insert into place (id, name, country_id) values (169, 'Moland', 169);
insert into place (id, name, country_id) values (170, 'Hintze', 170);
insert into place (id, name, country_id) values (171, 'Towne', 171);
insert into place (id, name, country_id) values (172, 'Veith', 172);
insert into place (id, name, country_id) values (173, 'South', 173);
insert into place (id, name, country_id) values (174, 'Hansons', 174);
insert into place (id, name, country_id) values (175, 'Morning', 175);
insert into place (id, name, country_id) values (176, 'Everett', 176);
insert into place (id, name, country_id) values (177, 'Glendale', 177);
insert into place (id, name, country_id) values (178, 'Golf', 178);
insert into place (id, name, country_id) values (179, 'Morrow', 179);
insert into place (id, name, country_id) values (180, 'Loomis', 180);
insert into place (id, name, country_id) values (181, 'Bunker Hill', 181);
insert into place (id, name, country_id) values (182, 'Holmberg', 182);
insert into place (id, name, country_id) values (183, 'Bunting', 183);
insert into place (id, name, country_id) values (184, 'Becker', 184);
insert into place (id, name, country_id) values (185, 'Utah', 185);
insert into place (id, name, country_id) values (186, 'Emmet', 186);
insert into place (id, name, country_id) values (187, 'Ilene', 187);
insert into place (id, name, country_id) values (188, 'Schlimgen', 188);
insert into place (id, name, country_id) values (189, 'Fieldstone', 189);
insert into place (id, name, country_id) values (190, 'Alpine', 190);
insert into place (id, name, country_id) values (191, 'Mandrake', 191);
insert into place (id, name, country_id) values (192, 'Hanover', 192);
insert into place (id, name, country_id) values (193, 'Portage', 193);
insert into place (id, name, country_id) values (194, 'David', 194);
insert into place (id, name, country_id) values (195, 'Browning', 195);
insert into place (id, name, country_id) values (196, 'Mendota', 196);
insert into place (id, name, country_id) values (197, 'Twin Pines', 197);
insert into place (id, name, country_id) values (198, 'Thackeray', 198);
insert into place (id, name, country_id) values (199, 'Artisan', 199);
insert into place (id, name, country_id) values (200, 'Pearson', 200);
insert into place (id, name, country_id) values (201, 'Bunting', 201);
insert into place (id, name, country_id) values (202, 'Kipling', 202);
insert into place (id, name, country_id) values (203, 'Utah', 203);
insert into place (id, name, country_id) values (204, 'Grayhawk', 204);
insert into place (id, name, country_id) values (205, 'Muir', 205);
insert into place (id, name, country_id) values (206, 'Cody', 206);
insert into place (id, name, country_id) values (207, 'Sloan', 207);
insert into place (id, name, country_id) values (208, 'Elka', 208);
insert into place (id, name, country_id) values (209, 'Harper', 209);
insert into place (id, name, country_id) values (210, 'Doe Crossing', 210);
insert into place (id, name, country_id) values (211, 'Mayfield', 211);
insert into place (id, name, country_id) values (212, 'Fuller', 212);
insert into place (id, name, country_id) values (213, 'Delladonna', 213);
insert into place (id, name, country_id) values (214, 'Bartillon', 214);
insert into place (id, name, country_id) values (215, 'East', 215);
insert into place (id, name, country_id) values (216, 'Hallows', 216);
insert into place (id, name, country_id) values (217, 'Independence', 217);
insert into place (id, name, country_id) values (218, 'Eggendart', 218);
insert into place (id, name, country_id) values (219, 'Macpherson', 219);
insert into place (id, name, country_id) values (220, 'Oxford', 220);
insert into place (id, name, country_id) values (221, 'Fuller', 221);
insert into place (id, name, country_id) values (222, 'Russell', 222);
insert into place (id, name, country_id) values (223, 'Birchwood', 223);
insert into place (id, name, country_id) values (224, 'Hansons', 224);
insert into place (id, name, country_id) values (225, 'Chive', 225);
insert into place (id, name, country_id) values (226, 'Kedzie', 226);
insert into place (id, name, country_id) values (227, 'Florence', 227);
insert into place (id, name, country_id) values (228, 'Anthes', 228);
insert into place (id, name, country_id) values (229, 'Algoma', 229);
insert into place (id, name, country_id) values (230, 'Center', 230);
insert into place (id, name, country_id) values (231, 'Dexter', 231);
insert into place (id, name, country_id) values (232, 'Everett', 232);
insert into place (id, name, country_id) values (233, 'Sachs', 233);
insert into place (id, name, country_id) values (234, 'Prairie Rose', 234);
insert into place (id, name, country_id) values (235, 'Scofield', 235);
insert into place (id, name, country_id) values (236, 'Schiller', 236);
insert into place (id, name, country_id) values (237, 'Stephen', 237);
insert into place (id, name, country_id) values (238, 'Lakewood Gardens', 238);
insert into place (id, name, country_id) values (239, 'Derek', 239);
insert into place (id, name, country_id) values (240, 'Pond', 240);
insert into place (id, name, country_id) values (241, 'Blackbird', 241);
insert into place (id, name, country_id) values (242, 'Katie', 242);
insert into place (id, name, country_id) values (243, 'Meadow Valley', 243);
insert into place (id, name, country_id) values (244, 'Bluejay', 244);
insert into place (id, name, country_id) values (245, 'Parkside', 245);
insert into place (id, name, country_id) values (246, 'Gina', 246);
insert into place (id, name, country_id) values (247, '7th', 247);
insert into place (id, name, country_id) values (248, 'Cardinal', 248);
insert into place (id, name, country_id) values (249, 'Sachtjen', 249);
insert into place (id, name, country_id) values (250, 'Prentice', 250);
insert into place (id, name, country_id) values (251, 'Old Gate', 251);
insert into place (id, name, country_id) values (252, 'Amoth', 252);
insert into place (id, name, country_id) values (253, 'Dawn', 253);
insert into place (id, name, country_id) values (254, 'Melrose', 254);
insert into place (id, name, country_id) values (255, 'Blackbird', 255);
insert into place (id, name, country_id) values (256, 'Montana', 256);
insert into place (id, name, country_id) values (257, 'Clemons', 257);
insert into place (id, name, country_id) values (258, 'Luster', 258);
insert into place (id, name, country_id) values (259, 'Ramsey', 259);
insert into place (id, name, country_id) values (260, 'Sunbrook', 260);
insert into place (id, name, country_id) values (261, 'Ryan', 261);
insert into place (id, name, country_id) values (262, 'Florence', 262);
insert into place (id, name, country_id) values (263, 'John Wall', 263);
insert into place (id, name, country_id) values (264, '6th', 264);
insert into place (id, name, country_id) values (265, 'International', 265);
insert into place (id, name, country_id) values (266, 'Hansons', 266);
insert into place (id, name, country_id) values (267, 'Melvin', 267);
insert into place (id, name, country_id) values (268, 'Grasskamp', 268);
insert into place (id, name, country_id) values (269, 'Meadow Vale', 269);
insert into place (id, name, country_id) values (270, 'Monica', 270);
insert into place (id, name, country_id) values (271, 'Lukken', 271);
insert into place (id, name, country_id) values (272, 'Gina', 272);
insert into place (id, name, country_id) values (273, 'Manufacturers', 273);
insert into place (id, name, country_id) values (274, 'Rusk', 274);
insert into place (id, name, country_id) values (275, 'Mifflin', 275);
insert into place (id, name, country_id) values (276, 'Bashford', 276);
insert into place (id, name, country_id) values (277, 'Crowley', 277);
insert into place (id, name, country_id) values (278, 'Steensland', 278);
insert into place (id, name, country_id) values (279, 'Ohio', 279);
insert into place (id, name, country_id) values (280, 'Thierer', 280);
insert into place (id, name, country_id) values (281, 'Kensington', 281);
insert into place (id, name, country_id) values (282, 'Spaight', 282);
insert into place (id, name, country_id) values (283, 'Lukken', 283);
insert into place (id, name, country_id) values (284, 'Basil', 284);
insert into place (id, name, country_id) values (285, 'Brentwood', 285);
insert into place (id, name, country_id) values (286, 'Gateway', 286);
insert into place (id, name, country_id) values (287, 'Kensington', 287);
insert into place (id, name, country_id) values (288, 'Green', 288);
insert into place (id, name, country_id) values (289, 'Hayes', 289);
insert into place (id, name, country_id) values (290, 'Harper', 290);
insert into place (id, name, country_id) values (291, 'Marcy', 291);
insert into place (id, name, country_id) values (292, 'Westport', 292);
insert into place (id, name, country_id) values (293, 'Gina', 293);
insert into place (id, name, country_id) values (294, 'Towne', 294);
insert into place (id, name, country_id) values (295, 'Morning', 295);
insert into place (id, name, country_id) values (296, 'Meadow Ridge', 296);
insert into place (id, name, country_id) values (297, 'Dayton', 297);
insert into place (id, name, country_id) values (298, 'Lawn', 298);
insert into place (id, name, country_id) values (299, '5th', 299);
insert into place (id, name, country_id) values (300, 'Schlimgen', 300);
insert into place (id, name, country_id) values (301, 'Sachs', 301);
insert into place (id, name, country_id) values (302, 'Redwing', 302);
insert into place (id, name, country_id) values (303, 'Hoard', 303);
insert into place (id, name, country_id) values (304, 'Sunbrook', 304);
insert into place (id, name, country_id) values (305, 'Sherman', 305);
insert into place (id, name, country_id) values (306, 'Melvin', 306);
insert into place (id, name, country_id) values (307, 'Pearson', 307);
insert into place (id, name, country_id) values (308, 'Sunbrook', 308);
insert into place (id, name, country_id) values (309, 'Crescent Oaks', 309);
insert into place (id, name, country_id) values (310, 'Nelson', 310);
insert into place (id, name, country_id) values (311, 'Sutteridge', 311);
insert into place (id, name, country_id) values (312, 'Debra', 312);
insert into place (id, name, country_id) values (313, 'Dapin', 313);
insert into place (id, name, country_id) values (314, 'Onsgard', 314);
insert into place (id, name, country_id) values (315, 'Sutherland', 315);
insert into place (id, name, country_id) values (316, 'Pepper Wood', 316);
insert into place (id, name, country_id) values (317, 'Shopko', 317);
insert into place (id, name, country_id) values (318, 'Colorado', 318);
insert into place (id, name, country_id) values (319, 'Bartelt', 319);
insert into place (id, name, country_id) values (320, 'Pawling', 320);
insert into place (id, name, country_id) values (321, 'Anderson', 321);
insert into place (id, name, country_id) values (322, 'Shoshone', 322);
insert into place (id, name, country_id) values (323, 'Oak', 323);
insert into place (id, name, country_id) values (324, 'Nancy', 324);
insert into place (id, name, country_id) values (325, 'Transport', 325);
insert into place (id, name, country_id) values (326, 'Valley Edge', 326);
insert into place (id, name, country_id) values (327, 'Dahle', 327);
insert into place (id, name, country_id) values (328, 'Monterey', 328);
insert into place (id, name, country_id) values (329, '6th', 329);
insert into place (id, name, country_id) values (330, 'Corscot', 330);
insert into place (id, name, country_id) values (331, 'Ilene', 331);
insert into place (id, name, country_id) values (332, 'Bellgrove', 332);
insert into place (id, name, country_id) values (333, 'Grover', 333);
insert into place (id, name, country_id) values (334, 'Sunfield', 334);
insert into place (id, name, country_id) values (335, 'Bonner', 335);
insert into place (id, name, country_id) values (336, 'John Wall', 336);
insert into place (id, name, country_id) values (337, 'Acker', 337);
insert into place (id, name, country_id) values (338, 'Coleman', 338);
insert into place (id, name, country_id) values (339, 'Nancy', 339);
insert into place (id, name, country_id) values (340, 'Fulton', 340);
insert into place (id, name, country_id) values (341, 'Karstens', 341);
insert into place (id, name, country_id) values (342, 'Petterle', 342);
insert into place (id, name, country_id) values (343, 'Onsgard', 343);
insert into place (id, name, country_id) values (344, 'Lunder', 344);
insert into place (id, name, country_id) values (345, 'Cherokee', 345);
insert into place (id, name, country_id) values (346, 'Amoth', 346);
insert into place (id, name, country_id) values (347, 'Mariners Cove', 347);
insert into place (id, name, country_id) values (348, 'Troy', 348);
insert into place (id, name, country_id) values (349, 'Jenifer', 349);
insert into place (id, name, country_id) values (350, 'Meadow Ridge', 350);
insert into place (id, name, country_id) values (351, 'Gale', 351);
insert into place (id, name, country_id) values (352, 'Shelley', 352);
insert into place (id, name, country_id) values (353, 'Fordem', 353);
insert into place (id, name, country_id) values (354, 'Corben', 354);
insert into place (id, name, country_id) values (355, 'Hoepker', 355);
insert into place (id, name, country_id) values (356, 'Service', 356);
insert into place (id, name, country_id) values (357, 'Hoffman', 357);
insert into place (id, name, country_id) values (358, 'Grasskamp', 358);
insert into place (id, name, country_id) values (359, 'John Wall', 359);
insert into place (id, name, country_id) values (360, 'Mcguire', 360);
insert into place (id, name, country_id) values (361, 'Morrow', 361);
insert into place (id, name, country_id) values (362, 'Portage', 362);
insert into place (id, name, country_id) values (363, 'Ludington', 363);
insert into place (id, name, country_id) values (364, 'Larry', 364);
insert into place (id, name, country_id) values (365, 'Mayfield', 365);
insert into place (id, name, country_id) values (366, 'Cardinal', 366);
insert into place (id, name, country_id) values (367, 'Glacier Hill', 367);
insert into place (id, name, country_id) values (368, '2nd', 368);
insert into place (id, name, country_id) values (369, 'Banding', 369);
insert into place (id, name, country_id) values (370, 'Doe Crossing', 370);
insert into place (id, name, country_id) values (371, 'Anthes', 371);
insert into place (id, name, country_id) values (372, 'Harbort', 372);
insert into place (id, name, country_id) values (373, 'Harper', 373);
insert into place (id, name, country_id) values (374, 'La Follette', 374);
insert into place (id, name, country_id) values (375, 'Mcbride', 375);
insert into place (id, name, country_id) values (376, 'Havey', 376);
insert into place (id, name, country_id) values (377, 'Chinook', 377);
insert into place (id, name, country_id) values (378, 'Rigney', 378);
insert into place (id, name, country_id) values (379, 'Fisk', 379);
insert into place (id, name, country_id) values (380, 'Huxley', 380);
insert into place (id, name, country_id) values (381, 'Melvin', 381);
insert into place (id, name, country_id) values (382, 'Mitchell', 382);
insert into place (id, name, country_id) values (383, 'Eagan', 383);
insert into place (id, name, country_id) values (384, 'Dahle', 384);
insert into place (id, name, country_id) values (385, 'Di Loreto', 385);
insert into place (id, name, country_id) values (386, 'Sommers', 386);
insert into place (id, name, country_id) values (387, 'Arizona', 387);
insert into place (id, name, country_id) values (388, 'Carioca', 388);
insert into place (id, name, country_id) values (389, 'Iowa', 389);
insert into place (id, name, country_id) values (390, 'Express', 390);
insert into place (id, name, country_id) values (391, 'Orin', 391);
insert into place (id, name, country_id) values (392, 'Elgar', 392);
insert into place (id, name, country_id) values (393, 'Pond', 393);
insert into place (id, name, country_id) values (394, 'Alpine', 394);
insert into place (id, name, country_id) values (395, 'Vahlen', 395);
insert into place (id, name, country_id) values (396, 'Magdeline', 396);
insert into place (id, name, country_id) values (397, 'Crescent Oaks', 397);
insert into place (id, name, country_id) values (398, 'Butterfield', 398);
insert into place (id, name, country_id) values (399, 'Meadow Ridge', 399);
insert into place (id, name, country_id) values (400, 'Jackson', 400);
insert into place (id, name, country_id) values (401, 'Knutson', 401);
insert into place (id, name, country_id) values (402, 'Randy', 402);
insert into place (id, name, country_id) values (403, 'Sundown', 403);
insert into place (id, name, country_id) values (404, 'Valley Edge', 404);
insert into place (id, name, country_id) values (405, 'Sugar', 405);
insert into place (id, name, country_id) values (406, 'Hallows', 406);
insert into place (id, name, country_id) values (407, 'Merchant', 407);
insert into place (id, name, country_id) values (408, 'Fisk', 408);
insert into place (id, name, country_id) values (409, 'Fairfield', 409);
insert into place (id, name, country_id) values (410, 'Haas', 410);
insert into place (id, name, country_id) values (411, 'Stone Corner', 411);
insert into place (id, name, country_id) values (412, 'Dahle', 412);
insert into place (id, name, country_id) values (413, 'Birchwood', 413);
insert into place (id, name, country_id) values (414, 'Bobwhite', 414);
insert into place (id, name, country_id) values (415, 'Forest Run', 415);
insert into place (id, name, country_id) values (416, 'Carberry', 416);
insert into place (id, name, country_id) values (417, 'Warner', 417);
insert into place (id, name, country_id) values (418, 'Charing Cross', 418);
insert into place (id, name, country_id) values (419, 'Old Shore', 419);
insert into place (id, name, country_id) values (420, 'Pierstorff', 420);
insert into place (id, name, country_id) values (421, 'Buhler', 421);
insert into place (id, name, country_id) values (422, 'Scott', 422);
insert into place (id, name, country_id) values (423, 'Shelley', 423);
insert into place (id, name, country_id) values (424, 'Oxford', 424);
insert into place (id, name, country_id) values (425, 'John Wall', 425);
insert into place (id, name, country_id) values (426, 'Shelley', 426);
insert into place (id, name, country_id) values (427, 'Granby', 427);
insert into place (id, name, country_id) values (428, 'Spohn', 428);
insert into place (id, name, country_id) values (429, 'Texas', 429);
insert into place (id, name, country_id) values (430, 'Little Fleur', 430);
insert into place (id, name, country_id) values (431, 'Algoma', 431);
insert into place (id, name, country_id) values (432, '8th', 432);
insert into place (id, name, country_id) values (433, 'Anniversary', 433);
insert into place (id, name, country_id) values (434, 'Sutherland', 434);
insert into place (id, name, country_id) values (435, '3rd', 435);
insert into place (id, name, country_id) values (436, 'Veith', 436);
insert into place (id, name, country_id) values (437, 'Farwell', 437);
insert into place (id, name, country_id) values (438, 'Express', 438);
insert into place (id, name, country_id) values (439, 'Paget', 439);
insert into place (id, name, country_id) values (440, 'Forster', 440);
insert into place (id, name, country_id) values (441, 'Toban', 441);
insert into place (id, name, country_id) values (442, 'Kings', 442);
insert into place (id, name, country_id) values (443, 'Transport', 443);
insert into place (id, name, country_id) values (444, 'Anhalt', 444);
insert into place (id, name, country_id) values (445, 'Onsgard', 445);
insert into place (id, name, country_id) values (446, 'Gulseth', 446);
insert into place (id, name, country_id) values (447, 'Judy', 447);
insert into place (id, name, country_id) values (448, 'Carberry', 448);
insert into place (id, name, country_id) values (449, 'Schlimgen', 449);
insert into place (id, name, country_id) values (450, 'Springs', 450);
insert into place (id, name, country_id) values (451, 'Esker', 451);
insert into place (id, name, country_id) values (452, 'Bunker Hill', 452);
insert into place (id, name, country_id) values (453, 'Summer Ridge', 453);
insert into place (id, name, country_id) values (454, 'Center', 454);
insert into place (id, name, country_id) values (455, 'Lakeland', 455);
insert into place (id, name, country_id) values (456, 'Briar Crest', 456);
insert into place (id, name, country_id) values (457, 'Holmberg', 457);
insert into place (id, name, country_id) values (458, 'Fulton', 458);
insert into place (id, name, country_id) values (459, 'Pennsylvania', 459);
insert into place (id, name, country_id) values (460, 'Eagan', 460);
insert into place (id, name, country_id) values (461, 'Eagle Crest', 461);
insert into place (id, name, country_id) values (462, 'Clarendon', 462);
insert into place (id, name, country_id) values (463, 'Northport', 463);
insert into place (id, name, country_id) values (464, 'Schlimgen', 464);
insert into place (id, name, country_id) values (465, 'Warrior', 465);
insert into place (id, name, country_id) values (466, 'Fair Oaks', 466);
insert into place (id, name, country_id) values (467, 'Algoma', 467);
insert into place (id, name, country_id) values (468, 'Briar Crest', 468);
insert into place (id, name, country_id) values (469, 'Pond', 469);
insert into place (id, name, country_id) values (470, 'Graceland', 470);
insert into place (id, name, country_id) values (471, 'Redwing', 471);
insert into place (id, name, country_id) values (472, 'Pleasure', 472);
insert into place (id, name, country_id) values (473, 'Mariners Cove', 473);
insert into place (id, name, country_id) values (474, 'Randy', 474);
insert into place (id, name, country_id) values (475, 'Park Meadow', 475);
insert into place (id, name, country_id) values (476, 'Manufacturers', 476);
insert into place (id, name, country_id) values (477, 'Rowland', 477);
insert into place (id, name, country_id) values (478, 'Steensland', 478);
insert into place (id, name, country_id) values (479, 'Del Mar', 479);
insert into place (id, name, country_id) values (480, 'Old Gate', 480);
insert into place (id, name, country_id) values (481, 'Shasta', 481);
insert into place (id, name, country_id) values (482, 'Toban', 482);
insert into place (id, name, country_id) values (483, 'Crowley', 483);
insert into place (id, name, country_id) values (484, 'Bultman', 484);
insert into place (id, name, country_id) values (485, 'Park Meadow', 485);
insert into place (id, name, country_id) values (486, 'Ridgeview', 486);
insert into place (id, name, country_id) values (487, 'Chinook', 487);
insert into place (id, name, country_id) values (488, 'Derek', 488);
insert into place (id, name, country_id) values (489, 'Texas', 489);
insert into place (id, name, country_id) values (490, 'Ludington', 490);
insert into place (id, name, country_id) values (491, 'Barby', 491);
insert into place (id, name, country_id) values (492, '6th', 492);
insert into place (id, name, country_id) values (493, 'Johnson', 493);
insert into place (id, name, country_id) values (494, 'Hoffman', 494);
insert into place (id, name, country_id) values (495, 'Dunning', 495);
insert into place (id, name, country_id) values (496, 'Alpine', 496);
insert into place (id, name, country_id) values (497, 'Hagan', 497);
insert into place (id, name, country_id) values (498, 'Sutherland', 498);
insert into place (id, name, country_id) values (499, 'Oakridge', 499);
insert into place (id, name, country_id) values (500, 'Forster', 500);
insert into place (id, name, country_id) values (501, 'Corry', 501);
insert into place (id, name, country_id) values (502, 'Redwing', 502);
insert into place (id, name, country_id) values (503, 'John Wall', 503);
insert into place (id, name, country_id) values (504, 'Buena Vista', 504);
insert into place (id, name, country_id) values (505, 'Caliangt', 505);
insert into place (id, name, country_id) values (506, 'Linden', 506);
insert into place (id, name, country_id) values (507, 'Rutledge', 507);
insert into place (id, name, country_id) values (508, 'Lake View', 508);
insert into place (id, name, country_id) values (509, 'Mcbride', 509);
insert into place (id, name, country_id) values (510, 'Ruskin', 510);
insert into place (id, name, country_id) values (511, 'Fairview', 511);
insert into place (id, name, country_id) values (512, 'Anhalt', 512);
insert into place (id, name, country_id) values (513, 'Jay', 513);
insert into place (id, name, country_id) values (514, 'Meadow Vale', 514);
insert into place (id, name, country_id) values (515, 'Roth', 515);
insert into place (id, name, country_id) values (516, 'Lake View', 516);
insert into place (id, name, country_id) values (517, '1st', 517);
insert into place (id, name, country_id) values (518, 'Gale', 518);
insert into place (id, name, country_id) values (519, 'Cardinal', 519);
insert into place (id, name, country_id) values (520, 'Trailsway', 520);
insert into place (id, name, country_id) values (521, 'Prairie Rose', 521);
insert into place (id, name, country_id) values (522, 'Hoepker', 522);
insert into place (id, name, country_id) values (523, 'Elgar', 523);
insert into place (id, name, country_id) values (524, 'Lighthouse Bay', 524);
insert into place (id, name, country_id) values (525, '4th', 525);
insert into place (id, name, country_id) values (526, 'Esker', 526);
insert into place (id, name, country_id) values (527, 'Jackson', 527);
insert into place (id, name, country_id) values (528, 'Alpine', 528);
insert into place (id, name, country_id) values (529, 'Donald', 529);
insert into place (id, name, country_id) values (530, 'Ohio', 530);
insert into place (id, name, country_id) values (531, 'Artisan', 531);
insert into place (id, name, country_id) values (532, 'Anthes', 532);
insert into place (id, name, country_id) values (533, 'Old Gate', 533);
insert into place (id, name, country_id) values (534, 'Hayes', 534);
insert into place (id, name, country_id) values (535, 'Northwestern', 535);
insert into place (id, name, country_id) values (536, 'Redwing', 536);
insert into place (id, name, country_id) values (537, 'Randy', 537);
insert into place (id, name, country_id) values (538, 'Bayside', 538);
insert into place (id, name, country_id) values (539, 'Sachtjen', 539);
insert into place (id, name, country_id) values (540, 'Tony', 540);
insert into place (id, name, country_id) values (541, 'Spohn', 541);
insert into place (id, name, country_id) values (542, 'Packers', 542);
insert into place (id, name, country_id) values (543, 'Fieldstone', 543);
insert into place (id, name, country_id) values (544, 'Thompson', 544);
insert into place (id, name, country_id) values (545, 'Anzinger', 545);
insert into place (id, name, country_id) values (546, 'Ruskin', 546);
insert into place (id, name, country_id) values (547, 'Toban', 547);
insert into place (id, name, country_id) values (548, 'Sherman', 548);
insert into place (id, name, country_id) values (549, 'Hudson', 549);
insert into place (id, name, country_id) values (550, 'Macpherson', 550);
insert into place (id, name, country_id) values (551, 'Montana', 551);
insert into place (id, name, country_id) values (552, 'Charing Cross', 552);
insert into place (id, name, country_id) values (553, 'Hanover', 553);
insert into place (id, name, country_id) values (554, 'Utah', 554);
insert into place (id, name, country_id) values (555, 'Anhalt', 555);
insert into place (id, name, country_id) values (556, 'Continental', 556);
insert into place (id, name, country_id) values (557, 'Loftsgordon', 557);
insert into place (id, name, country_id) values (558, 'Warner', 558);
insert into place (id, name, country_id) values (559, 'Harbort', 559);
insert into place (id, name, country_id) values (560, 'High Crossing', 560);
insert into place (id, name, country_id) values (561, 'Talmadge', 561);
insert into place (id, name, country_id) values (562, 'Larry', 562);
insert into place (id, name, country_id) values (563, 'Holy Cross', 563);
insert into place (id, name, country_id) values (564, 'Hansons', 564);
insert into place (id, name, country_id) values (565, 'Melrose', 565);
insert into place (id, name, country_id) values (566, '4th', 566);
insert into place (id, name, country_id) values (567, 'Vahlen', 567);
insert into place (id, name, country_id) values (568, 'Hooker', 568);
insert into place (id, name, country_id) values (569, 'Rowland', 569);
insert into place (id, name, country_id) values (570, 'Kennedy', 570);
insert into place (id, name, country_id) values (571, 'Merrick', 571);
insert into place (id, name, country_id) values (572, 'Rutledge', 572);
insert into place (id, name, country_id) values (573, 'Veith', 573);
insert into place (id, name, country_id) values (574, 'American Ash', 574);
insert into place (id, name, country_id) values (575, 'Hermina', 575);
insert into place (id, name, country_id) values (576, 'Kensington', 576);
insert into place (id, name, country_id) values (577, 'Meadow Valley', 577);
insert into place (id, name, country_id) values (578, 'Hintze', 578);
insert into place (id, name, country_id) values (579, 'Everett', 579);
insert into place (id, name, country_id) values (580, 'Morningstar', 580);
insert into place (id, name, country_id) values (581, 'Mesta', 581);
insert into place (id, name, country_id) values (582, 'Dexter', 582);
insert into place (id, name, country_id) values (583, 'Fulton', 583);
insert into place (id, name, country_id) values (584, 'Charing Cross', 584);
insert into place (id, name, country_id) values (585, 'Stone Corner', 585);
insert into place (id, name, country_id) values (586, 'Burning Wood', 586);
insert into place (id, name, country_id) values (587, 'Ludington', 587);
insert into place (id, name, country_id) values (588, 'Ohio', 588);
insert into place (id, name, country_id) values (589, 'Mallard', 589);
insert into place (id, name, country_id) values (590, 'Debra', 590);
insert into place (id, name, country_id) values (591, 'Shelley', 591);
insert into place (id, name, country_id) values (592, 'Garrison', 592);
insert into place (id, name, country_id) values (593, 'Stoughton', 593);
insert into place (id, name, country_id) values (594, 'Kings', 594);
insert into place (id, name, country_id) values (595, 'Pearson', 595);
insert into place (id, name, country_id) values (596, 'Ryan', 596);
insert into place (id, name, country_id) values (597, 'Saint Paul', 597);
insert into place (id, name, country_id) values (598, 'Menomonie', 598);
insert into place (id, name, country_id) values (599, 'Hansons', 599);
insert into place (id, name, country_id) values (600, 'Harper', 600);
insert into place (id, name, country_id) values (601, 'Schurz', 601);
insert into place (id, name, country_id) values (602, 'Cascade', 602);
insert into place (id, name, country_id) values (603, 'Meadow Vale', 603);
insert into place (id, name, country_id) values (604, 'Porter', 604);
insert into place (id, name, country_id) values (605, 'Delladonna', 605);
insert into place (id, name, country_id) values (606, 'Hermina', 606);
insert into place (id, name, country_id) values (607, 'Kim', 607);
insert into place (id, name, country_id) values (608, 'Coolidge', 608);
insert into place (id, name, country_id) values (609, 'Harbort', 609);
insert into place (id, name, country_id) values (610, 'Cody', 610);
insert into place (id, name, country_id) values (611, 'Stuart', 611);
insert into place (id, name, country_id) values (612, 'Messerschmidt', 612);
insert into place (id, name, country_id) values (613, 'Randy', 613);
insert into place (id, name, country_id) values (614, 'Vermont', 614);
insert into place (id, name, country_id) values (615, 'Ruskin', 615);
insert into place (id, name, country_id) values (616, 'Schiller', 616);
insert into place (id, name, country_id) values (617, 'Kennedy', 617);
insert into place (id, name, country_id) values (618, 'Ohio', 618);
insert into place (id, name, country_id) values (619, 'Old Gate', 619);
insert into place (id, name, country_id) values (620, 'Gina', 620);
insert into place (id, name, country_id) values (621, 'Jana', 621);
insert into place (id, name, country_id) values (622, 'Carpenter', 622);
insert into place (id, name, country_id) values (623, 'Di Loreto', 623);
insert into place (id, name, country_id) values (624, 'Crownhardt', 624);
insert into place (id, name, country_id) values (625, 'Burning Wood', 625);
insert into place (id, name, country_id) values (626, 'Chive', 626);
insert into place (id, name, country_id) values (627, 'Homewood', 627);
insert into place (id, name, country_id) values (628, 'Garrison', 628);
insert into place (id, name, country_id) values (629, 'Sugar', 629);
insert into place (id, name, country_id) values (630, 'Fordem', 630);
insert into place (id, name, country_id) values (631, 'Golf View', 631);
insert into place (id, name, country_id) values (632, 'Forest Dale', 632);
insert into place (id, name, country_id) values (633, 'Dottie', 633);
insert into place (id, name, country_id) values (634, 'Fallview', 634);
insert into place (id, name, country_id) values (635, 'Ronald Regan', 635);
insert into place (id, name, country_id) values (636, 'Bellgrove', 636);
insert into place (id, name, country_id) values (637, 'Crescent Oaks', 637);
insert into place (id, name, country_id) values (638, 'Hanover', 638);
insert into place (id, name, country_id) values (639, 'Corry', 639);
insert into place (id, name, country_id) values (640, 'Lakeland', 640);
insert into place (id, name, country_id) values (641, 'Memorial', 641);
insert into place (id, name, country_id) values (642, 'Veith', 642);
insert into place (id, name, country_id) values (643, 'Maple Wood', 643);
insert into place (id, name, country_id) values (644, 'Lillian', 644);
insert into place (id, name, country_id) values (645, 'Golden Leaf', 645);
insert into place (id, name, country_id) values (646, 'Susan', 646);
insert into place (id, name, country_id) values (647, 'Lyons', 647);
insert into place (id, name, country_id) values (648, 'Annamark', 648);
insert into place (id, name, country_id) values (649, 'Dovetail', 649);
insert into place (id, name, country_id) values (650, 'Northland', 650);
insert into place (id, name, country_id) values (651, 'Melrose', 651);
insert into place (id, name, country_id) values (652, 'Stephen', 652);
insert into place (id, name, country_id) values (653, 'Oriole', 653);
insert into place (id, name, country_id) values (654, 'Huxley', 654);
insert into place (id, name, country_id) values (655, 'Brown', 655);
insert into place (id, name, country_id) values (656, 'Donald', 656);
insert into place (id, name, country_id) values (657, 'Lotheville', 657);
insert into place (id, name, country_id) values (658, 'Rusk', 658);
insert into place (id, name, country_id) values (659, 'Debs', 659);
insert into place (id, name, country_id) values (660, 'Hanson', 660);
insert into place (id, name, country_id) values (661, 'Park Meadow', 661);
insert into place (id, name, country_id) values (662, 'Veith', 662);
insert into place (id, name, country_id) values (663, 'Armistice', 663);
insert into place (id, name, country_id) values (664, 'Oakridge', 664);
insert into place (id, name, country_id) values (665, 'Rigney', 665);
insert into place (id, name, country_id) values (666, 'Esker', 666);
insert into place (id, name, country_id) values (667, 'Brickson Park', 667);
insert into place (id, name, country_id) values (668, 'Forest Run', 668);
insert into place (id, name, country_id) values (669, 'Heath', 669);
insert into place (id, name, country_id) values (670, 'Valley Edge', 670);
insert into place (id, name, country_id) values (671, 'Fairview', 671);
insert into place (id, name, country_id) values (672, 'Charing Cross', 672);
insert into place (id, name, country_id) values (673, 'Grasskamp', 673);
insert into place (id, name, country_id) values (674, 'Maryland', 674);
insert into place (id, name, country_id) values (675, 'Superior', 675);
insert into place (id, name, country_id) values (676, 'Dovetail', 676);
insert into place (id, name, country_id) values (677, 'Sloan', 677);
insert into place (id, name, country_id) values (678, 'Burrows', 678);
insert into place (id, name, country_id) values (679, 'Rowland', 679);
insert into place (id, name, country_id) values (680, 'Northridge', 680);
insert into place (id, name, country_id) values (681, 'Warner', 681);
insert into place (id, name, country_id) values (682, 'Texas', 682);
insert into place (id, name, country_id) values (683, 'Kim', 683);
insert into place (id, name, country_id) values (684, 'Colorado', 684);
insert into place (id, name, country_id) values (685, 'Banding', 685);
insert into place (id, name, country_id) values (686, 'Lien', 686);
insert into place (id, name, country_id) values (687, 'Morrow', 687);
insert into place (id, name, country_id) values (688, 'Burning Wood', 688);
insert into place (id, name, country_id) values (689, 'Northwestern', 689);
insert into place (id, name, country_id) values (690, 'Dapin', 690);
insert into place (id, name, country_id) values (691, 'Bay', 691);
insert into place (id, name, country_id) values (692, 'Oriole', 692);
insert into place (id, name, country_id) values (693, 'Magdeline', 693);
insert into place (id, name, country_id) values (694, 'Parkside', 694);
insert into place (id, name, country_id) values (695, 'Lunder', 695);
insert into place (id, name, country_id) values (696, 'Mitchell', 696);
insert into place (id, name, country_id) values (697, 'Spaight', 697);
insert into place (id, name, country_id) values (698, 'Old Gate', 698);
insert into place (id, name, country_id) values (699, 'Golf View', 699);
insert into place (id, name, country_id) values (700, 'Redwing', 700);
insert into place (id, name, country_id) values (701, 'Merchant', 701);
insert into place (id, name, country_id) values (702, 'Mifflin', 702);
insert into place (id, name, country_id) values (703, 'Carey', 703);
insert into place (id, name, country_id) values (704, 'Gulseth', 704);
insert into place (id, name, country_id) values (705, '7th', 705);
insert into place (id, name, country_id) values (706, 'Schmedeman', 706);
insert into place (id, name, country_id) values (707, 'Mccormick', 707);
insert into place (id, name, country_id) values (708, 'Algoma', 708);
insert into place (id, name, country_id) values (709, 'Summerview', 709);
insert into place (id, name, country_id) values (710, 'Boyd', 710);
insert into place (id, name, country_id) values (711, 'Holy Cross', 711);
insert into place (id, name, country_id) values (712, 'Heffernan', 712);
insert into place (id, name, country_id) values (713, 'Shopko', 713);
insert into place (id, name, country_id) values (714, 'Carpenter', 714);
insert into place (id, name, country_id) values (715, 'Maple Wood', 715);
insert into place (id, name, country_id) values (716, 'Leroy', 716);
insert into place (id, name, country_id) values (717, 'Northport', 717);
insert into place (id, name, country_id) values (718, 'Messerschmidt', 718);
insert into place (id, name, country_id) values (719, 'Nelson', 719);
insert into place (id, name, country_id) values (720, 'Southridge', 720);
insert into place (id, name, country_id) values (721, 'Northview', 721);
insert into place (id, name, country_id) values (722, 'Anthes', 722);
insert into place (id, name, country_id) values (723, 'North', 723);
insert into place (id, name, country_id) values (724, 'Evergreen', 724);
insert into place (id, name, country_id) values (725, 'Eliot', 725);
insert into place (id, name, country_id) values (726, 'Fulton', 726);
insert into place (id, name, country_id) values (727, 'Nevada', 727);
insert into place (id, name, country_id) values (728, 'Moose', 728);
insert into place (id, name, country_id) values (729, 'Dayton', 729);
insert into place (id, name, country_id) values (730, 'Anzinger', 730);
insert into place (id, name, country_id) values (731, 'Mockingbird', 731);
insert into place (id, name, country_id) values (732, 'Ridge Oak', 732);
insert into place (id, name, country_id) values (733, 'Carpenter', 733);
insert into place (id, name, country_id) values (734, 'Delladonna', 734);
insert into place (id, name, country_id) values (735, 'Meadow Valley', 735);
insert into place (id, name, country_id) values (736, 'Corben', 736);
insert into place (id, name, country_id) values (737, 'Sage', 737);
insert into place (id, name, country_id) values (738, 'Burrows', 738);
insert into place (id, name, country_id) values (739, 'Harbort', 739);
insert into place (id, name, country_id) values (740, 'Fairfield', 740);
insert into place (id, name, country_id) values (741, 'Randy', 741);
insert into place (id, name, country_id) values (742, 'Jenna', 742);
insert into place (id, name, country_id) values (743, 'Thompson', 743);
insert into place (id, name, country_id) values (744, 'Moulton', 744);
insert into place (id, name, country_id) values (745, 'Rusk', 745);
insert into place (id, name, country_id) values (746, 'Graceland', 746);
insert into place (id, name, country_id) values (747, 'Colorado', 747);
insert into place (id, name, country_id) values (748, 'Thierer', 748);
insert into place (id, name, country_id) values (749, 'Lighthouse Bay', 749);
insert into place (id, name, country_id) values (750, 'Homewood', 750);
insert into place (id, name, country_id) values (751, 'Kings', 751);
insert into place (id, name, country_id) values (752, 'Troy', 752);
insert into place (id, name, country_id) values (753, 'Becker', 753);
insert into place (id, name, country_id) values (754, 'Clove', 754);
insert into place (id, name, country_id) values (755, 'Mariners Cove', 755);
insert into place (id, name, country_id) values (756, 'Knutson', 756);
insert into place (id, name, country_id) values (757, 'Dawn', 757);
insert into place (id, name, country_id) values (758, 'Hovde', 758);
insert into place (id, name, country_id) values (759, 'Barnett', 759);
insert into place (id, name, country_id) values (760, 'Corben', 760);
insert into place (id, name, country_id) values (761, 'Cottonwood', 761);
insert into place (id, name, country_id) values (762, 'Delaware', 762);
insert into place (id, name, country_id) values (763, 'Sommers', 763);
insert into place (id, name, country_id) values (764, 'Crowley', 764);
insert into place (id, name, country_id) values (765, 'Garrison', 765);
insert into place (id, name, country_id) values (766, 'Transport', 766);
insert into place (id, name, country_id) values (767, 'Dunning', 767);
insert into place (id, name, country_id) values (768, 'Logan', 768);
insert into place (id, name, country_id) values (769, 'Prairie Rose', 769);
insert into place (id, name, country_id) values (770, 'Aberg', 770);
insert into place (id, name, country_id) values (771, 'Cottonwood', 771);
insert into place (id, name, country_id) values (772, 'Harbort', 772);
insert into place (id, name, country_id) values (773, 'Evergreen', 773);
insert into place (id, name, country_id) values (774, 'Eliot', 774);
insert into place (id, name, country_id) values (775, 'Dovetail', 775);
insert into place (id, name, country_id) values (776, 'Vahlen', 776);
insert into place (id, name, country_id) values (777, 'Stang', 777);
insert into place (id, name, country_id) values (778, 'Lunder', 778);
insert into place (id, name, country_id) values (779, 'Grayhawk', 779);
insert into place (id, name, country_id) values (780, 'Havey', 780);
insert into place (id, name, country_id) values (781, 'Charing Cross', 781);
insert into place (id, name, country_id) values (782, 'Hauk', 782);
insert into place (id, name, country_id) values (783, 'Prairieview', 783);
insert into place (id, name, country_id) values (784, 'Texas', 784);
insert into place (id, name, country_id) values (785, 'Rockefeller', 785);
insert into place (id, name, country_id) values (786, 'Hanson', 786);
insert into place (id, name, country_id) values (787, 'Kedzie', 787);
insert into place (id, name, country_id) values (788, 'Lunder', 788);
insert into place (id, name, country_id) values (789, 'Portage', 789);
insert into place (id, name, country_id) values (790, '1st', 790);
insert into place (id, name, country_id) values (791, 'Crest Line', 791);
insert into place (id, name, country_id) values (792, 'Loeprich', 792);
insert into place (id, name, country_id) values (793, 'Park Meadow', 793);
insert into place (id, name, country_id) values (794, 'Roxbury', 794);
insert into place (id, name, country_id) values (795, 'Waxwing', 795);
insert into place (id, name, country_id) values (796, 'Transport', 796);
insert into place (id, name, country_id) values (797, 'Acker', 797);
insert into place (id, name, country_id) values (798, 'Nevada', 798);
insert into place (id, name, country_id) values (799, 'Oxford', 799);
insert into place (id, name, country_id) values (800, 'Mitchell', 800);
insert into place (id, name, country_id) values (801, 'Ruskin', 801);
insert into place (id, name, country_id) values (802, 'Towne', 802);
insert into place (id, name, country_id) values (803, 'Stoughton', 803);
insert into place (id, name, country_id) values (804, 'Banding', 804);
insert into place (id, name, country_id) values (805, 'Eastlawn', 805);
insert into place (id, name, country_id) values (806, 'Monica', 806);
insert into place (id, name, country_id) values (807, 'New Castle', 807);
insert into place (id, name, country_id) values (808, 'Sunnyside', 808);
insert into place (id, name, country_id) values (809, 'Schiller', 809);
insert into place (id, name, country_id) values (810, 'Eastlawn', 810);
insert into place (id, name, country_id) values (811, 'Eagan', 811);
insert into place (id, name, country_id) values (812, 'Utah', 812);
insert into place (id, name, country_id) values (813, 'Dottie', 813);
insert into place (id, name, country_id) values (814, 'Melody', 814);
insert into place (id, name, country_id) values (815, 'Toban', 815);
insert into place (id, name, country_id) values (816, 'Bluestem', 816);
insert into place (id, name, country_id) values (817, 'Anhalt', 817);
insert into place (id, name, country_id) values (818, 'Ryan', 818);
insert into place (id, name, country_id) values (819, 'Corben', 819);
insert into place (id, name, country_id) values (820, 'Corscot', 820);
insert into place (id, name, country_id) values (821, 'Nelson', 821);
insert into place (id, name, country_id) values (822, 'Maple Wood', 822);
insert into place (id, name, country_id) values (823, 'Dahle', 823);
insert into place (id, name, country_id) values (824, 'Tomscot', 824);
insert into place (id, name, country_id) values (825, 'Stephen', 825);
insert into place (id, name, country_id) values (826, 'Merchant', 826);
insert into place (id, name, country_id) values (827, 'Clyde Gallagher', 827);
insert into place (id, name, country_id) values (828, 'Gina', 828);
insert into place (id, name, country_id) values (829, 'Hooker', 829);
insert into place (id, name, country_id) values (830, 'Marquette', 830);
insert into place (id, name, country_id) values (831, 'Stephen', 831);
insert into place (id, name, country_id) values (832, 'Crowley', 832);
insert into place (id, name, country_id) values (833, 'Kensington', 833);
insert into place (id, name, country_id) values (834, 'Memorial', 834);
insert into place (id, name, country_id) values (835, 'Dayton', 835);
insert into place (id, name, country_id) values (836, 'Bartelt', 836);
insert into place (id, name, country_id) values (837, 'Service', 837);
insert into place (id, name, country_id) values (838, 'Shopko', 838);
insert into place (id, name, country_id) values (839, 'Montana', 839);
insert into place (id, name, country_id) values (840, 'Dorton', 840);
insert into place (id, name, country_id) values (841, 'Anderson', 841);
insert into place (id, name, country_id) values (842, 'Declaration', 842);
insert into place (id, name, country_id) values (843, 'Dayton', 843);
insert into place (id, name, country_id) values (844, 'Hanover', 844);
insert into place (id, name, country_id) values (845, 'Park Meadow', 845);
insert into place (id, name, country_id) values (846, 'Carey', 846);
insert into place (id, name, country_id) values (847, 'Kim', 847);
insert into place (id, name, country_id) values (848, 'Coleman', 848);
insert into place (id, name, country_id) values (849, 'Pine View', 849);
insert into place (id, name, country_id) values (850, 'Village Green', 850);
insert into place (id, name, country_id) values (851, 'Thackeray', 851);
insert into place (id, name, country_id) values (852, 'Sunfield', 852);
insert into place (id, name, country_id) values (853, '8th', 853);
insert into place (id, name, country_id) values (854, 'Badeau', 854);
insert into place (id, name, country_id) values (855, 'Rigney', 855);
insert into place (id, name, country_id) values (856, 'Lakeland', 856);
insert into place (id, name, country_id) values (857, 'Golf', 857);
insert into place (id, name, country_id) values (858, 'Florence', 858);
insert into place (id, name, country_id) values (859, 'Dennis', 859);
insert into place (id, name, country_id) values (860, 'Texas', 860);
insert into place (id, name, country_id) values (861, 'Russell', 861);
insert into place (id, name, country_id) values (862, 'Artisan', 862);
insert into place (id, name, country_id) values (863, 'Arkansas', 863);
insert into place (id, name, country_id) values (864, 'Schurz', 864);
insert into place (id, name, country_id) values (865, 'Gateway', 865);
insert into place (id, name, country_id) values (866, 'Erie', 866);
insert into place (id, name, country_id) values (867, 'Katie', 867);
insert into place (id, name, country_id) values (868, 'Fulton', 868);
insert into place (id, name, country_id) values (869, 'Fordem', 869);
insert into place (id, name, country_id) values (870, 'Fordem', 870);
insert into place (id, name, country_id) values (871, 'Straubel', 871);
insert into place (id, name, country_id) values (872, 'Milwaukee', 872);
insert into place (id, name, country_id) values (873, 'La Follette', 873);
insert into place (id, name, country_id) values (874, 'Loomis', 874);
insert into place (id, name, country_id) values (875, 'Sugar', 875);
insert into place (id, name, country_id) values (876, 'Morningstar', 876);
insert into place (id, name, country_id) values (877, 'Eagan', 877);
insert into place (id, name, country_id) values (878, 'Redwing', 878);
insert into place (id, name, country_id) values (879, 'Shelley', 879);
insert into place (id, name, country_id) values (880, 'Acker', 880);
insert into place (id, name, country_id) values (881, 'Marcy', 881);
insert into place (id, name, country_id) values (882, 'Northfield', 882);
insert into place (id, name, country_id) values (883, 'Paget', 883);
insert into place (id, name, country_id) values (884, 'Garrison', 884);
insert into place (id, name, country_id) values (885, 'Jana', 885);
insert into place (id, name, country_id) values (886, 'Pine View', 886);
insert into place (id, name, country_id) values (887, 'Knutson', 887);
insert into place (id, name, country_id) values (888, 'Coolidge', 888);
insert into place (id, name, country_id) values (889, 'Oriole', 889);
insert into place (id, name, country_id) values (890, 'Oak Valley', 890);
insert into place (id, name, country_id) values (891, 'Homewood', 891);
insert into place (id, name, country_id) values (892, 'Moose', 892);
insert into place (id, name, country_id) values (893, 'Fieldstone', 893);
insert into place (id, name, country_id) values (894, 'Melrose', 894);
insert into place (id, name, country_id) values (895, 'Green', 895);
insert into place (id, name, country_id) values (896, 'Sunfield', 896);
insert into place (id, name, country_id) values (897, 'Dryden', 897);
insert into place (id, name, country_id) values (898, 'Calypso', 898);
insert into place (id, name, country_id) values (899, 'Summit', 899);
insert into place (id, name, country_id) values (900, 'La Follette', 900);
insert into place (id, name, country_id) values (901, 'Annamark', 901);
insert into place (id, name, country_id) values (902, 'Maryland', 902);
insert into place (id, name, country_id) values (903, 'Oxford', 903);
insert into place (id, name, country_id) values (904, 'Dexter', 904);
insert into place (id, name, country_id) values (905, 'Forster', 905);
insert into place (id, name, country_id) values (906, 'Ronald Regan', 906);
insert into place (id, name, country_id) values (907, 'Prentice', 907);
insert into place (id, name, country_id) values (908, 'Meadow Vale', 908);
insert into place (id, name, country_id) values (909, 'Schlimgen', 909);
insert into place (id, name, country_id) values (910, 'Kropf', 910);
insert into place (id, name, country_id) values (911, 'Roxbury', 911);
insert into place (id, name, country_id) values (912, 'Dayton', 912);
insert into place (id, name, country_id) values (913, 'Stang', 913);
insert into place (id, name, country_id) values (914, 'Cardinal', 914);
insert into place (id, name, country_id) values (915, '2nd', 915);
insert into place (id, name, country_id) values (916, 'Dahle', 916);
insert into place (id, name, country_id) values (917, 'Magdeline', 917);
insert into place (id, name, country_id) values (918, 'Loomis', 918);
insert into place (id, name, country_id) values (919, 'Prairie Rose', 919);
insert into place (id, name, country_id) values (920, 'Utah', 920);
insert into place (id, name, country_id) values (921, 'Doe Crossing', 921);
insert into place (id, name, country_id) values (922, 'Kipling', 922);
insert into place (id, name, country_id) values (923, 'Elka', 923);
insert into place (id, name, country_id) values (924, 'Browning', 924);
insert into place (id, name, country_id) values (925, 'Bellgrove', 925);
insert into place (id, name, country_id) values (926, 'Memorial', 926);
insert into place (id, name, country_id) values (927, 'Declaration', 927);
insert into place (id, name, country_id) values (928, 'Clove', 928);
insert into place (id, name, country_id) values (929, 'Kedzie', 929);
insert into place (id, name, country_id) values (930, 'Coolidge', 930);
insert into place (id, name, country_id) values (931, 'South', 931);
insert into place (id, name, country_id) values (932, 'Morningstar', 932);
insert into place (id, name, country_id) values (933, 'Quincy', 933);
insert into place (id, name, country_id) values (934, 'Green', 934);
insert into place (id, name, country_id) values (935, 'Chinook', 935);
insert into place (id, name, country_id) values (936, 'Nelson', 936);
insert into place (id, name, country_id) values (937, 'Pepper Wood', 937);
insert into place (id, name, country_id) values (938, 'Dennis', 938);
insert into place (id, name, country_id) values (939, 'Corscot', 939);
insert into place (id, name, country_id) values (940, 'Fallview', 940);
insert into place (id, name, country_id) values (941, 'Utah', 941);
insert into place (id, name, country_id) values (942, 'Chinook', 942);
insert into place (id, name, country_id) values (943, 'Katie', 943);
insert into place (id, name, country_id) values (944, 'Briar Crest', 944);
insert into place (id, name, country_id) values (945, 'Esker', 945);
insert into place (id, name, country_id) values (946, 'Cherokee', 946);
insert into place (id, name, country_id) values (947, 'Sommers', 947);
insert into place (id, name, country_id) values (948, 'Iowa', 948);
insert into place (id, name, country_id) values (949, 'Lighthouse Bay', 949);
insert into place (id, name, country_id) values (950, 'Logan', 950);
insert into place (id, name, country_id) values (951, 'Corry', 951);
insert into place (id, name, country_id) values (952, 'Memorial', 952);
insert into place (id, name, country_id) values (953, 'Hallows', 953);
insert into place (id, name, country_id) values (954, 'Fulton', 954);
insert into place (id, name, country_id) values (955, 'Twin Pines', 955);
insert into place (id, name, country_id) values (956, 'Anthes', 956);
insert into place (id, name, country_id) values (957, 'Clove', 957);
insert into place (id, name, country_id) values (958, 'Eagan', 958);
insert into place (id, name, country_id) values (959, 'Loftsgordon', 959);
insert into place (id, name, country_id) values (960, 'Clemons', 960);
insert into place (id, name, country_id) values (961, 'Riverside', 961);
insert into place (id, name, country_id) values (962, '1st', 962);
insert into place (id, name, country_id) values (963, 'Village', 963);
insert into place (id, name, country_id) values (964, 'Golden Leaf', 964);
insert into place (id, name, country_id) values (965, 'Bayside', 965);
insert into place (id, name, country_id) values (966, 'Quincy', 966);
insert into place (id, name, country_id) values (967, 'Chive', 967);
insert into place (id, name, country_id) values (968, 'Express', 968);
insert into place (id, name, country_id) values (969, 'Morningstar', 969);
insert into place (id, name, country_id) values (970, 'Forster', 970);
insert into place (id, name, country_id) values (971, 'Browning', 971);
insert into place (id, name, country_id) values (972, 'Dottie', 972);
insert into place (id, name, country_id) values (973, 'Welch', 973);
insert into place (id, name, country_id) values (974, 'Kropf', 974);
insert into place (id, name, country_id) values (975, 'Nevada', 975);
insert into place (id, name, country_id) values (976, 'Judy', 976);
insert into place (id, name, country_id) values (977, 'Laurel', 977);
insert into place (id, name, country_id) values (978, 'Linden', 978);
insert into place (id, name, country_id) values (979, 'Bluejay', 979);
insert into place (id, name, country_id) values (980, 'Red Cloud', 980);
insert into place (id, name, country_id) values (981, 'Clyde Gallagher', 981);
insert into place (id, name, country_id) values (982, 'Maple', 982);
insert into place (id, name, country_id) values (983, 'Elgar', 983);
insert into place (id, name, country_id) values (984, 'Bayside', 984);
insert into place (id, name, country_id) values (985, 'Forest', 985);
insert into place (id, name, country_id) values (986, 'Dayton', 986);
insert into place (id, name, country_id) values (987, 'Warrior', 987);
insert into place (id, name, country_id) values (988, 'Bayside', 988);
insert into place (id, name, country_id) values (989, 'Sloan', 989);
insert into place (id, name, country_id) values (990, 'Boyd', 990);
insert into place (id, name, country_id) values (991, 'Chinook', 991);
insert into place (id, name, country_id) values (992, 'Kinsman', 992);
insert into place (id, name, country_id) values (993, 'Fairview', 993);
insert into place (id, name, country_id) values (994, 'Kings', 994);
insert into place (id, name, country_id) values (995, 'Saint Paul', 995);
insert into place (id, name, country_id) values (996, 'Utah', 996);
insert into place (id, name, country_id) values (997, 'Lerdahl', 997);
insert into place (id, name, country_id) values (998, 'Browning', 998);
insert into place (id, name, country_id) values (999, 'Hauk', 999);
insert into place (id, name, country_id) values (1000, 'Mendota', 1000);
